export const COLORS = {
  background: "#000000",
  text: "#ffffff",
  secondaryText: "#000",
  border: "white",
  checkbox: "#03b1fc",
  button: "#0099ff",
  darkButton: "#282828",
  darkButtonHighlight: "#2e2e2e",
  buttonText: "#fff",
  workoutListText: "#ccccff",
  textInputBackground: "#ccccff",
  placeholderText: "#666",
  saveButton: "#16a055",
  disabledButton: "#d7deda",
  disabledButtonText: "#888",
  createButtonColor: "#946eff",
  secondaryBackground: "#ccccff",
};
